<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Bai_1.aspx.cs" Inherits="Bai_1" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .style1
        {
            font-size: xx-large;
        }
        .style2
        {
            font-size: large;
        }
        .style3
        {
            color: #0000FF;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server" class="style1">
    <strong style="color: #000099">GridView : Xem Thêm Xóa Sửa Dữ Liệu<hr />
    </strong><span class="style3">
    <br class="style2" />
    </span><span class="style2"><span class="style3">Thông tin sinh viên<asp:GridView 
        ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" 
        DataKeyNames="MSSV" DataSourceID="SqlDataSource1" ForeColor="#333333" 
        GridLines="None" ShowFooter="True">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:TemplateField HeaderText="Mã SV" SortExpression="MSSV">
                <EditItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Eval("MSSV") %>'></asp:Label>
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="txtMSSV" runat="server"></asp:TextBox>
                </FooterTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("MSSV") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Họ" SortExpression="Ho">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Ho") %>'></asp:TextBox>
                </EditItemTemplate>
                <FooterTemplate>
                    <span class="style2"><span class="style3">
                    <asp:TextBox ID="txtHo" runat="server"></asp:TextBox>
                    </span></span>
                </FooterTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("Ho") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Tên" SortExpression="Ten">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Ten") %>'></asp:TextBox>
                </EditItemTemplate>
                <FooterTemplate>
                    <span class="style2"><span class="style3">
                    <asp:TextBox ID="txtTen" runat="server"></asp:TextBox>
                    </span></span>
                </FooterTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("Ten") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Ngày Sinh" SortExpression="NgaySinh">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("NgaySinh") %>'></asp:TextBox>
                </EditItemTemplate>
                <FooterTemplate>
                    <span class="style2"><span class="style3">
                    <asp:TextBox ID="txtNgaySinh" runat="server"></asp:TextBox>
                    </span></span>
                </FooterTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("NgaySinh") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Giới Tính" SortExpression="GioiTinh">
                <EditItemTemplate>
                    <asp:CheckBox ID="CheckBox1" runat="server" Checked='<%# Bind("GioiTinh") %>' />
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:CheckBox ID="chkGioiTinh" runat="server" />
                </FooterTemplate>
                <ItemTemplate>
                    <asp:CheckBox ID="CheckBox1" runat="server" Checked='<%# Bind("GioiTinh") %>' 
                        Enabled="false" />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Mã Lớp" SortExpression="MaLop">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("MaLop") %>'></asp:TextBox>
                </EditItemTemplate>
                <FooterTemplate>
                    <span class="style2"><span class="style3">
                    <asp:TextBox ID="txtMaLop" runat="server"></asp:TextBox>
                    </span></span>
                </FooterTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label5" runat="server" Text='<%# Bind("MaLop") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Tên Lớp" SortExpression="TenLop">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("TenLop") %>'></asp:TextBox>
                </EditItemTemplate>
                <FooterTemplate>
                    <asp:LinkButton ID="lbtnInsert" runat="server" ForeColor="Yellow" 
                        onclick="lbtnInsert_Click">Insert</asp:LinkButton>
                </FooterTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label6" runat="server" Text='<%# Bind("TenLop") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <EditRowStyle BackColor="#2461BF" />
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F5F7FB" />
        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
        <SortedDescendingCellStyle BackColor="#E9EBEF" />
        <SortedDescendingHeaderStyle BackColor="#4870BE" />
    </asp:GridView>
    <br />
    </span>
    <asp:Label ID="Label1" runat="server"></asp:Label>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
        DeleteCommand="DELETE SinhVien WHERE MSSV = @MSSV" 
        InsertCommand="INSERT INTO SinhVien VALUES(@MSSV, @Ho, @Ten, @NgaySinh, @GioiTinh, @MaLop, @TenLop)" 
        SelectCommand="SELECT SinhVien.*, TenLop FROM SinhVien, Lop WHERE SinhVien.MaLop = Lop.MaLop" 
        UpdateCommand="UPDATE SinhVien SET Ho = @Ho, Ten = @Ten, NgaySinh = @NgaySinh, GioiTinh = @GioiTinh, MaLop = @MaLop WHERE MSSV = @MSSV">
        <DeleteParameters>
            <asp:Parameter Name="MSSV" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="MSSV" />
            <asp:Parameter Name="Ho" />
            <asp:Parameter Name="Ten" />
            <asp:Parameter Name="NgaySinh" />
            <asp:Parameter Name="GioiTinh" />
            <asp:Parameter Name="MaLop" />
            <asp:Parameter Name="TenLop" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Ho" />
            <asp:Parameter Name="Ten" />
            <asp:Parameter Name="NgaySinh" />
            <asp:Parameter Name="GioiTinh" />
            <asp:Parameter Name="MaLop" />
            <asp:Parameter Name="MSSV" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <br />
    </span>
    </form>
</body>
</html>
